// app/RootLayout.js

import { Roboto } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";
import Footer from "./_components/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "SUPERMARKET",
  description: "Generated by create next app SUPERMARKET",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased `}>
        <Header></Header>
        <div className="w-11/12 mx-auto my-10">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
